version: '3.8'
services:
  dev_server:
    profiles: ["dev_server"]
    build:
      context: .
      target: dev_server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "./apps/server/src:/app/server/src"
    env_file:
      - "./apps/server/.env"

  prod_server:
    profiles: ["prod_server"]
    build:
      context: .
      target: prod_server
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - "./apps/server/.env"
    environment:
      - PORT=80
    image: us-east4-docker.pkg.dev/sodium-cat-347501/test-server/server

  dev_web:
    profiles: ["dev_web"]
    build:
      context: .
      target: dev_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./apps/web/src:/app/web/src"

  prod_web:
    profiles: ["prod_web"]
    build:
      context: .
      target: prod_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    image: us-east4-docker.pkg.dev/sodium-cat-347501/test-client/web
